# Site settings
title: web前端学习笔记
email: hancong9104@163.com
description: > # this means to ignore newlines until "baseurl:"
  绿螘新醅酒，红泥小火炉。<br>晚来天欲雪，能饮一杯无？
baseurl: "/blogs"
url: "http://insekkei.com/blogs/"
github_username:  insekkei

# Build settings
markdown: kramdown

# paginate settings
paginate: 8
paginate_path: "/blogs/page:num"
